import { Inter } from "next/font/google";
import "./globals.css";
import ProductProvider from "@/components/Context";
import Navigation from "@/components/Navigation";
import { ToastContainer } from "react-toastify";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ProductProvider>
        <body className={inter.className}>
          <Navigation />
          <main className={"main"}>
            {children}
            <ToastContainer position="bottom-right" autoClose={5000} />
          </main>
        </body>
      </ProductProvider>
    </html>
  );
}
